#!/bin/sh

LED="/sys/class/leds/green:wan"
[ -d "$LED" ] || exit 0

case "$ACTION:$INTERFACE" in
	ifup:modem)
		echo none > "$LED/trigger"
		echo 1 > "$LED/brightness"
		;;
	ifdown:modem)
		echo none > "$LED/trigger"
		echo 0 > "$LED/brightness"
		;;
esac
